@startuml

title Example API Schemas Diagram

entity ExampleModel {
    Name: String
}

entity GetExampleCall200Response {
    Message: String
    Items: List<GetExampleCall200ResponseItemsInner>
    Count: String
}

entity GetExampleCall200ResponseItemsInner {
    Name: String
}


GetExampleCall200Response -- "0..*" GetExampleCall200ResponseItemsInner : Items

@enduml