// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Example API
 *
 * Example API spec
 *
 * API version: v1
 * Contact: example@example-team.com
 */

package openapi

import (
	"context"
	"net/http"
)



// ExampleCallAPIRouter defines the required methods for binding the api requests to a responses for the ExampleCallAPI
// The ExampleCallAPIRouter implementation should parse necessary information from the http request,
// pass the data to a ExampleCallAPIServicer to perform the required actions, then write the service results to the http response.
type ExampleCallAPIRouter interface { 
	GetChildrenByExampleParentId(http.ResponseWriter, *http.Request)
	GetExampleParentById(http.ResponseWriter, *http.Request)
	GetExamples(http.ResponseWriter, *http.Request)
}


// ExampleCallAPIServicer defines the api actions for the ExampleCallAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ExampleCallAPIServicer interface { 
	GetChildrenByExampleParentId(context.Context, string, int32) (ImplResponse, error)
	GetExampleParentById(context.Context, string, int32) (ImplResponse, error)
	GetExamples(context.Context, int32) (ImplResponse, error)
}
