// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Example API
 *
 * Example API spec
 *
 * API version: v1
 * Contact: example@example-team.com
 */

package openapi




type GetChildrenByExampleParentId500Response struct {

	// Message response string.
	Message string `json:"Message,omitempty"`

	// Array of ExampleChildModel objects returned, but API error returns empty array.
	Items []ExampleChildModel `json:"Items,omitempty"`

	// Count of objects returned, null if error occured.
	Count *string `json:"Count,omitempty"`
}

// AssertGetChildrenByExampleParentId500ResponseRequired checks if the required fields are not zero-ed
func AssertGetChildrenByExampleParentId500ResponseRequired(obj GetChildrenByExampleParentId500Response) error {
	for _, el := range obj.Items {
		if err := AssertExampleChildModelRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertGetChildrenByExampleParentId500ResponseConstraints checks if the values respects the defined constraints
func AssertGetChildrenByExampleParentId500ResponseConstraints(obj GetChildrenByExampleParentId500Response) error {
	return nil
}
