// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Example API
 *
 * Example API spec
 *
 * API version: v1
 * Contact: example@example-team.com
 */

package openapi




type GetExampleParentById500Response struct {

	// Message response string.
	Message string `json:"Message,omitempty"`

	// Array of objects returned, but API error returns empty array.
	Parent []ExampleParentModel `json:"Parent,omitempty"`

	// Count of objects returned, null if error occured.
	Count *string `json:"Count,omitempty"`
}

// AssertGetExampleParentById500ResponseRequired checks if the required fields are not zero-ed
func AssertGetExampleParentById500ResponseRequired(obj GetExampleParentById500Response) error {
	for _, el := range obj.Parent {
		if err := AssertExampleParentModelRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertGetExampleParentById500ResponseConstraints checks if the values respects the defined constraints
func AssertGetExampleParentById500ResponseConstraints(obj GetExampleParentById500Response) error {
	return nil
}
