// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Example API
 *
 * Example API spec
 *
 * API version: v1
 * Contact: example@example-team.com
 */

package openapi




type GetExamplesSimple200Response struct {

	// Message response string.
	Message string `json:"Message,omitempty"`
}

// AssertGetExamplesSimple200ResponseRequired checks if the required fields are not zero-ed
func AssertGetExamplesSimple200ResponseRequired(obj GetExamplesSimple200Response) error {
	return nil
}

// AssertGetExamplesSimple200ResponseConstraints checks if the values respects the defined constraints
func AssertGetExamplesSimple200ResponseConstraints(obj GetExamplesSimple200Response) error {
	return nil
}
