// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Example API
 *
 * Example API spec
 *
 * API version: v1
 * Contact: example@example-team.com
 */

package openapi




type GetExamples200Response struct {

	// Message response string.
	Message string `json:"Message,omitempty"`

	// Array of objects returned.
	Items []ExampleParentModel `json:"Items,omitempty"`

	// Count of objects returned, null if error occured.
	Count *string `json:"Count,omitempty"`
}

// AssertGetExamples200ResponseRequired checks if the required fields are not zero-ed
func AssertGetExamples200ResponseRequired(obj GetExamples200Response) error {
	for _, el := range obj.Items {
		if err := AssertExampleParentModelRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertGetExamples200ResponseConstraints checks if the values respects the defined constraints
func AssertGetExamples200ResponseConstraints(obj GetExamples200Response) error {
	return nil
}
