// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Example API
 *
 * Example API spec
 *
 * API version: v1
 * Contact: example@example-team.com
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/YOUR-USERNAME-OR-GITHUB-ORG/YOUR-GENERATED-CLIENT-REPO/go"
)

func main() {
	log.Printf("Server started")

	ExampleCallAPIService := openapi.NewExampleCallAPIService()
	ExampleCallAPIController := openapi.NewExampleCallAPIController(ExampleCallAPIService)

	router := openapi.NewRouter(ExampleCallAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
