# coding: utf-8

"""
    Example API

    Example API spec

    The version of the OpenAPI document: v1
    Contact: example@example-team.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.example_child_model import ExampleChildModel

class TestExampleChildModel(unittest.TestCase):
    """ExampleChildModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExampleChildModel:
        """Test ExampleChildModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExampleChildModel`
        """
        model = ExampleChildModel()
        if include_optional:
            return ExampleChildModel(
                child_id = '5c06345b-eb66-4f31-84ed-42847b630133',
                child_name = 'Example child name 1',
                parents = [
                    {ParentId=f59e24c1-8d57-4ad3-b6e7-8577fc117269, ParentName=Example parent name 1}
                    ]
            )
        else:
            return ExampleChildModel(
        )
        """

    def testExampleChildModel(self):
        """Test ExampleChildModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
