# coding: utf-8

"""
    Example API

    Example API spec

    The version of the OpenAPI document: v1
    Contact: example@example-team.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_children_with_pets_by_example_parent_id200_response import GetChildrenWithPetsByExampleParentId200Response

class TestGetChildrenWithPetsByExampleParentId200Response(unittest.TestCase):
    """GetChildrenWithPetsByExampleParentId200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetChildrenWithPetsByExampleParentId200Response:
        """Test GetChildrenWithPetsByExampleParentId200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetChildrenWithPetsByExampleParentId200Response`
        """
        model = GetChildrenWithPetsByExampleParentId200Response()
        if include_optional:
            return GetChildrenWithPetsByExampleParentId200Response(
                message = 'Results found',
                items = [{"ModelType":"ExampleChildWithDog","ChildId":"5c06345b-eb66-4f31-84ed-42847b630133","ChildName":"Example child name 1","DogName":"Bones"},{"ModelType":"ExampleChildWithCat","ChildId":"5c06345b-eb66-4f31-84ed-42847b630133","ChildName":"Example child name 2","CatName":"Snowball"}],
                count = ''
            )
        else:
            return GetChildrenWithPetsByExampleParentId200Response(
        )
        """

    def testGetChildrenWithPetsByExampleParentId200Response(self):
        """Test GetChildrenWithPetsByExampleParentId200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
