# coding: utf-8

"""
    Example API

    Example API spec

    The version of the OpenAPI document: v1
    Contact: example@example-team.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.example_parent_model import ExampleParentModel

class TestExampleParentModel(unittest.TestCase):
    """ExampleParentModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExampleParentModel:
        """Test ExampleParentModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExampleParentModel`
        """
        model = ExampleParentModel()
        if include_optional:
            return ExampleParentModel(
                parent_id = 'f59e24c1-8d57-4ad3-b6e7-8577fc117269',
                parent_name = 'Example parent name 1'
            )
        else:
            return ExampleParentModel(
        )
        """

    def testExampleParentModel(self):
        """Test ExampleParentModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
