# coding: utf-8

"""
    Example API

    Example API spec

    The version of the OpenAPI document: v1
    Contact: example@example-team.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_example_parent_by_id500_response import GetExampleParentById500Response

class TestGetExampleParentById500Response(unittest.TestCase):
    """GetExampleParentById500Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetExampleParentById500Response:
        """Test GetExampleParentById500Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetExampleParentById500Response`
        """
        model = GetExampleParentById500Response()
        if include_optional:
            return GetExampleParentById500Response(
                message = 'Results found',
                parent = [{ParentId=f59e24c1-8d57-4ad3-b6e7-8577fc117269, ParentName=Example parent name 1}, {ParentId=128583d9-2517-43c2-a9f0-1ad4cad687cd, ParentName=Example parent name 2}],
                count = ''
            )
        else:
            return GetExampleParentById500Response(
        )
        """

    def testGetExampleParentById500Response(self):
        """Test GetExampleParentById500Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
